name: unlockd_fake_provider
description: A Unlock'd Flutter package created by Unlock'd.
version: 0.0.2
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  unlockd_bluetooth_core:
    git:
      url: git@github.com:Unlock-d/unlockd_bluetooth.git
      path: unlockd_bluetooth_core
      ref: v2.1.0

dev_dependencies:
  mocktail: ^1.0.0
  very_good_analysis: ^5.0.0
