name: unlockd_fake_adapter
description: A Unlock'd Flutter package created by Unlock'd.
version: 0.2.6
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.10.0

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  unlockd_bluetooth_core:
    git:
      url: git@github.com:Unlock-d/unlockd_bluetooth.git
      path: unlockd_bluetooth_core
      ref: v2.4.2

dev_dependencies:
  fake_async: ^1.3.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.0.0
