name: example
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  unlockd_bluetooth_core:
    git:
      url: git@github.com:Unlock-d/unlockd_bluetooth.git
      path: unlockd_bluetooth_core
      ref: v2.0.0
  unlockd_flutter_blue_plus_provider:
    git:
      url: git@github.com:Unlock-d/unlockd_bluetooth.git
      path: bluetooth_providers/unlockd_flutter_blue_plus_provider
      ref: v2.0.0
  unlockd_isar_provider:
    git:
      url: git@github.com:Unlock-d/unlockd_bluetooth.git
      path: bluetooth_providers/unlockd_isar_provider
      ref: v2.0.0
  permission_handler: ^11.0.0
  isar: ^3.1.0+1
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  injectable_generator: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/