name: unlockd_bluetooth

packages:
  - bluetooth_providers/*
  - unlockd_bluetooth_core
  - unlockd_bluetooth_devtools_extension
  - example

scripts:
  pub-get:
    run: flutter pub get
    description: Run Dart tests for all packages in the project.
    exec:
      concurrency: 1

  test:
    run: flutter test --test-randomize-ordering-seed=random
    description: Run Dart tests for all packages in the project.
    exec:
      failFast: true