name: unlockd_bluetooth
description: A Very Good Project created by Very Good CLI.
version: 1.0.3
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.10.0

dependencies:
  device_info_plus: ^9.1.1
  fast_immutable_collections: ^9.2.0
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.31.7
  fpdart: ^1.1.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  logging: ^1.2.0
  path_provider: ^2.1.2
  watcher: ^1.1.0

dev_dependencies:
  build_runner: any
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  mocktail: ^1.0.0
  very_good_analysis: ^5.0.0
