name: unlockd_bluetooth
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.10.0

dependencies:
  device_info_plus: ^9.1.1
  fast_immutable_collections: ^9.2.0
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.31.7
  fpdart: ^1.1.0
  logging: ^1.2.0
  watcher: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.0.0
