name: unlockd_bluetooth_core
description: The core package for the unlockd bluetooth.
version: 2.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.10.0

dependencies:
  device_info_plus: ^9.1.1
  fast_immutable_collections: ^9.2.0
  flutter:
    sdk: flutter
  fpdart: ^1.1.0
  logger: ^2.0.2+1
  logging: ^1.2.0
  nordic_dfu: ^6.0.1
  path_provider: ^2.1.2
  watcher: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.0.0
