name: unlockd_bluetooth_core
description: The core package for the unlockd bluetooth.
version: 2.4.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.10.0

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  logging: ^1.2.0
  nordic_dfu: 6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.0.0
