name: unlockd_isar_provider
description: A Unlock'd Flutter package created by Unlock'd.
version: 0.1.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.10.0

dependencies:
  flutter:
    sdk: flutter
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  unlockd_bluetooth_core:
    git:
      url: git@github.com:Unlock-d/unlockd_bluetooth.git
      path: unlockd_bluetooth_core
      ref: v2.3.1

dev_dependencies:
  build_runner: any
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  mocktail: ^1.0.0
  very_good_analysis: ^5.0.0
