name: CI

concurrency:
  group: $-$
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    uses: Unlock-d/unlockd_workflows/.github/workflows/unlockd_flutter_package.yaml@v1.1
    secrets:
      ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
    with:
      flutter_channel: stable
      min_coverage: 80
      test_optimization: false
